apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: aby2m4xt7-java-quarkus-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/aby2m4xt7-java-quarkus-gitops